name: Sync to repo1

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo2
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Set up Git
      run: |
        git config --global user.name 'Hitesh'
        git config --global user.email 'hitesh@gmail.com'

    - name: Add repo1 remote
      run: git remote add repo1 https://ram-wappnet:${{ secrets.REPO1_TOKEN }}@github.com/ram-wappnet/repo1.git

    - name: Push to repo1
      run: |
        git fetch repo1
        git push repo1 main
